In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt
import akshare as ak
from tqdm import tqdm
from datetime import datetime, timedelta
from collections import Counter
from quant_utils import midterm_entry_signal_backtrack,backtest_single_stock
from pathlib import Path
import tushare as ts

ts.set_token("103ef331836d4a8aa5d7485665c8f7503b8632c23748f1ba985c5713")
pro = ts.pro_api("103ef331836d4a8aa5d7485665c8f7503b8632c23748f1ba985c5713")

In [6]:
#单只股票的测试

code = "000001"

df = ak.stock_zh_a_hist(
    symbol=code,
    period="daily",
    adjust="qfq",
)
df['MA20'] = df['收盘'].rolling(20).mean()
df['MA60'] = df['收盘'].rolling(60).mean()

rets = backtest_single_stock(df)

print("信号次数:", len(rets))
print("平均收益:", np.mean(rets))
print("胜率:", np.mean(np.array(rets) > 0))

ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

In [73]:
df

,日期,股票代码,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率,MA20,MA60
0,1991-04-03,000001,-2.72,-2.72,-2.72,-2.72,1,5.000000e+03,0.00,2.86,0.08,0.00,NaN,NaN
1,1991-04-04,000001,-2.73,-2.73,-2.73,-2.73,3,1.500000e+04,0.00,-0.37,-0.01,0.00,NaN,NaN
2,1991-04-05,000001,-2.73,-2.73,-2.73,-2.73,2,1.000000e+04,0.00,0.00,0.00,0.00,NaN,NaN
3,1991-04-06,000001,-2.73,-2.73,-2.73,-2.73,7,3.400000e+04,0.00,0.00,0.00,0.00,NaN,NaN
4,1991-04-08,000001,-2.73,-2.73,-2.73,-2.73,2,1.000000e+04,0.00,0.00,0.00,0.00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8334,2026-02-09,000001,11.05,11.07,11.11,11.01,619717,6.852182e+08,0.90,0.18,0.02,0.32,11.0575,11.400333
8335,2026-02-10,000001,11.07,11.06,11.10,11.02,600430,6.641402e+08,0.72,-0.09,-0.01,0.31,11.0370,11.388833
8336,2026-02-11,000001,11.06,11.07,11.09,11.02,431041,4.768019e+08,0.63,0.09,0.01,0.22,11.0225,11.378833
8337,2026-02-12,000001,11.07,10.96,11.08,10.93,681340,7.483385e+08,1.36,-0.99,-0.11,0.35,11.0050,11.368333
8338,2026-02-13,000001,10.96,10.91,10.99,10.90,555047,6.075014e+08,0.82,-0.46,-0.05,0.29,10.9910,11.353500

In [3]:
all_rets = []
stock_results = []

for _, row in tqdm(stock_list.iterrows(), total=len(stock_list)):
    code = row['code']
    
    try:
        df = ak.stock_zh_a_hist(
            symbol=code,
            period="daily",
            adjust="qfq",
        )
        
        if df.shape[0] < 100:
            continue
        
        df['MA20'] = df['收盘'].rolling(20).mean()
        df['MA60'] = df['收盘'].rolling(60).mean()

        rets = backtest_single_stock(df)

        if len(rets) == 0:
            continue

        all_rets.extend(rets)

        stock_results.append({
            "code": code,
            "信号次数": len(rets),
            "平均收益": np.mean(rets),
            "胜率": np.mean(np.array(rets) > 0)
        })

    except:
        continue


# ===== 整体统计 =====
print("总信号次数:", len(all_rets))
print("整体平均收益:", np.mean(all_rets))
print("整体胜率:", np.mean(np.array(all_rets) > 0))

100%|██████████| 100/100 [01:43<00:00,  1.03s/it]

总信号次数: 0
整体平均收益: nan
整体胜率: nan

/Users/ciciliu/anaconda3/envs/quant/lib/python3.10/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/ciciliu/anaconda3/envs/quant/lib/python3.10/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

In [13]:
stock_list = pd.read_csv("/Users/ciciliu/stock_analysis/data/mainboard_with_ts_code.csv",dtype={"code": "string"})
stock_list = stock_list.head(1000)
stock_list

       code   name board    ts_code
0    000001   平安银行   深主板  000001.SZ
1    000002  万  科Ａ   深主板  000002.SZ
2    000004  *ST国华   深主板  000004.SZ
3    000006   深振业Ａ   深主板  000006.SZ
4    000007    全新好   深主板  000007.SZ
..      ...    ...   ...        ...
995  002500   山西证券   深主板  002500.SZ
996  002501   利源股份   深主板  002501.SZ
997  002506   协鑫集成   深主板  002506.SZ
998  002507   涪陵榨菜   深主板  002507.SZ
999  002508   老板电器   深主板  002508.SZ

[1000 rows x 4 columns]

In [22]:
BY_STOCK_DIR = Path("/Users/ciciliu/stock_analysis/data/by_stock")

all_rets = []
stock_results = []
failed = []

# keep only needed columns from stock_list
cols = ["code"] + ["ts_code"] 
rows_df = stock_list[cols].copy()

# Last 25 years cutoff
cutoff_date = pd.Timestamp.today().normalize() - pd.DateOffset(years=25)

for row in tqdm(rows_df.itertuples(index=False), total=len(rows_df)):
    code = row.code
    ts_code = row.ts_code
    
    local_path = BY_STOCK_DIR / f"{ts_code}.parquet"
    if not local_path.exists():
        continue

    try:
        # read only required columns
        df = pd.read_parquet(local_path, columns=["trade_date", "close", "low", "vol"])

        # keep only last 25 years
        df["trade_date"] = pd.to_datetime(df["trade_date"], errors="coerce")
        df = df[df["trade_date"] >= cutoff_date]
        if len(df) < 100:
            continue

        df = df.sort_values("trade_date")
        df["MA20"] = df["close"].rolling(20).mean()
        df["MA60"] = df["close"].rolling(60).mean()

        rets = backtest_single_stock(df)  # backtest should use English cols now
        if not rets:
            continue

        all_rets.extend(rets)
        stock_results.append({
            "code": code,
            "ts_code": ts_code,
            "信号次数": len(rets),
            "平均收益": float(np.mean(rets)),
            "胜率": float(np.mean(np.array(rets) > 0)),
        })

    except Exception as e:
        failed.append((ts_code, str(e)))

print("failed:", len(failed))

100%|██████████| 1000/1000 [06:20<00:00,  2.63it/s]

failed: 0

In [ ]:
rows_df

       code    ts_code
0    000001  000001.SZ
1    000002  000002.SZ
2    000006  000006.SZ
3    000007  000007.SZ
4    000008  000008.SZ
..      ...        ...
995  002557  002557.SZ
996  002558  002558.SZ
997  002559  002559.SZ
998  002560  002560.SZ
999  002561  002561.SZ

[1000 rows x 2 columns]

In [23]:
#all_rets = [r for r in all_rets if abs(r) < 1]
wins = [r for r in all_rets if r > 0]
losses = [r for r in all_rets if r <= 0]

print("平均盈利:", np.mean(wins))
print("平均亏损:", np.mean(losses))
print("盈亏比:", abs(np.mean(wins) / np.mean(losses)))

平均盈利: 0.16531351283679405
平均亏损: -0.05282621805099478
盈亏比: 3.129383835072422

In [24]:
print("最大盈利:", np.max(all_rets))
print("最大亏损:", np.min(all_rets))

最大盈利: 3.7665580890336585
最大亏损: -0.6766743648960739

In [25]:
win_rate = len(wins) / len(all_rets) if len(rets) > 0 else np.nan
print("胜率:", win_rate)

胜率: 0.3275477239353891

In [6]:
stock_results

[{'code': '000001',
  'ts_code': '000001.SZ',
  '信号次数': 84,
  '平均收益': 0.01382230012252882,
  '胜率': 0.32142857142857145},
 {'code': '000002',
  'ts_code': '000002.SZ',
  '信号次数': 90,
  '平均收益': 0.031230936849909983,
  '胜率': 0.3888888888888889},
 {'code': '000006',
  'ts_code': '000006.SZ',
  '信号次数': 82,
  '平均收益': 0.03971712144887467,
  '胜率': 0.3780487804878049},
 {'code': '000007',
  'ts_code': '000007.SZ',
  '信号次数': 85,
  '平均收益': 0.028543192246946892,
  '胜率': 0.4470588235294118},
 {'code': '000008',
  'ts_code': '000008.SZ',
  '信号次数': 75,
  '平均收益': 0.16218402353175548,
  '胜率': 0.6533333333333333},
 {'code': '000009',
  'ts_code': '000009.SZ',
  '信号次数': 79,
  '平均收益': 0.08406417689514069,
  '胜率': 0.4050632911392405},
 {'code': '000010',
  'ts_code': '000010.SZ',
  '信号次数': 56,
  '平均收益': -0.03145060013621176,
  '胜率': 0.19642857142857142},
 {'code': '000011',
  'ts_code': '000011.SZ',
  '信号次数': 60,
  '平均收益': 0.004449420625480585,
  '胜率': 0.21666666666666667},
 {'code': '000012',
  'ts_code': '000012.SZ',
  '信号次数': 66,
  '平均收益': -0.0008608191082271418,
  '胜率': 0.30303030303030304},
 {'code': '000014',
  'ts_code': '000014.SZ',
  '信号次数': 59,
  '平均收益': 0.01950914306242521,
  '胜率': 0.4576271186440678},
 {'code': '000016',
  'ts_code': '000016.SZ',
  '信号次数': 64,
  '平均收益': 0.09227299797278438,
  '胜率': 0.40625},
 {'code': '000017',
  'ts_code': '000017.SZ',
  '信号次数': 37,
  '平均收益': -0.021617017568876268,
  '胜率': 0.13513513513513514},
 {'code': '000019',
  'ts_code': '000019.SZ',
  '信号次数': 63,
  '平均收益': 0.042712708718796975,
  '胜率': 0.4444444444444444},
 {'code': '000020',
  'ts_code': '000020.SZ',
  '信号次数': 46,
  '平均收益': -0.0012722293961987413,
  '胜率': 0.2391304347826087},
 {'code': '000021',
  'ts_code': '000021.SZ',
  '信号次数': 81,
  '平均收益': 0.03283223309387714,
  '胜率': 0.38271604938271603},
 {'code': '000025',
  'ts_code': '000025.SZ',
  '信号次数': 58,
  '平均收益': 0.06928160967644793,
  '胜率': 0.39655172413793105},
 {'code': '000026',
  'ts_code': '000026.SZ',
  '信号次数': 60,
  '平均收益': 0.019926033474886067,
  '胜率': 0.23333333333333334},
 {'code': '000027',
  'ts_code': '000027.SZ',
  '信号次数': 66,
  '平均收益': 0.05787832752311567,
  '胜率': 0.3787878787878788},
 {'code': '000028',
  'ts_code': '000028.SZ',
  '信号次数': 64,
  '平均收益': -0.005392783052340454,
  '胜率': 0.3125},
 {'code': '000029',
  'ts_code': '000029.SZ',
  '信号次数': 56,
  '平均收益': 0.03873514410596928,
  '胜率': 0.39285714285714285},
 {'code': '000030',
  'ts_code': '000030.SZ',
  '信号次数': 49,
  '平均收益': -0.011070660596484953,
  '胜率': 0.24489795918367346},
 {'code': '000031',
  'ts_code': '000031.SZ',
  '信号次数': 55,
  '平均收益': 0.030600046828723693,
  '胜率': 0.41818181818181815},
 {'code': '000032',
  'ts_code': '000032.SZ',
  '信号次数': 64,
  '平均收益': 0.009779939940511247,
  '胜率': 0.234375},
 {'code': '000034',
  'ts_code': '000034.SZ',
  '信号次数': 73,
  '平均收益': 0.10832451594718369,
  '胜率': 0.410958904109589},
 {'code': '000035',
  'ts_code': '000035.SZ',
  '信号次数': 53,
  '平均收益': -0.020874493954819853,
  '胜率': 0.41509433962264153},
 {'code': '000036',
  'ts_code': '000036.SZ',
  '信号次数': 70,
  '平均收益': -0.025560051843882752,
  '胜率': 0.2857142857142857},
 {'code': '000037',
  'ts_code': '000037.SZ',
  '信号次数': 56,
  '平均收益': -0.013627558626633715,
  '胜率': 0.2857142857142857},
 {'code': '000039',
  'ts_code': '000039.SZ',
  '信号次数': 71,
  '平均收益': 0.011842563037680573,
  '胜率': 0.4647887323943662},
 {'code': '000042',
  'ts_code': '000042.SZ',
  '信号次数': 81,
  '平均收益': 0.008348663581555815,
  '胜率': 0.2716049382716049},
 {'code': '000045',
  'ts_code': '000045.SZ',
  '信号次数': 43,
  '平均收益': -0.014752290534835658,
  '胜率': 0.32558139534883723},
 {'code': '000048',
  'ts_code': '000048.SZ',
  '信号次数': 78,
  '平均收益': 0.027497795651965147,
  '胜率': 0.3333333333333333},
 {'code': '000049',
  'ts_code': '000049.SZ',
  '信号次数': 56,
  '平均收益': -0.0170980735957665,
  '胜率': 0.16071428571428573},
 {'code': '000050',
  'ts_code': '000050.SZ',
  '信号次数': 48,
  '平均收益': 0.006429253126126816,
  '胜率': 0.3541666666666667},
 {'code': '000055',
  'ts_code': '000055.SZ',
  '信号次数': 58,
  '平均收益': -0.009455988284074584,
  '胜率': 0.25862068965517243},
 {'code': '000056',
  'ts_code': '000056.SZ',
  '信号次数': 48,
  '平均收益': -0.040062951396486746,
  '胜率': 0.20833333333333334},
 {'code': '000058',
  'ts_code': '000058.SZ',
  '信号次数': 57,
  '平均收益': 0.04957567126879829,
  '胜率': 0.49122807017543857},
 {'code': '000059',
  'ts_code': '000059.SZ',
  '信号次数': 41,
  '平均收益': -0.017988015680746563,
  '胜率': 0.12195121951219512},
 {'code': '000060',
  'ts_code': '000060.SZ',
  '信号次数': 84,
  '平均收益': -0.01638247116479167,
  '胜率': 0.21428571428571427},
 {'code': '000061',
  'ts_code': '000061.SZ',
  '信号次数': 45,
  '平均收益': 0.06665743089521008,
  '胜率': 0.5111111111111111},
 {'code': '000062',
  'ts_code': '000062.SZ',
  '信号次数': 41,
  '平均收益': 0.17046148721693138,
  '胜率': 0.3170731707317073},
 {'code': '000063',
  'ts_code': '000063.SZ',
  '信号次数': 67,
  '平均收益': -0.005086155202426196,
  '胜率': 0.2835820895522388},
 {'code': '000065',
  'ts_code': '000065.SZ',
  '信号次数': 56,
  '平均收益': 0.003730140263919972,
  '胜率': 0.2857142857142857},
 {'code': '000066',
  'ts_code': '000066.SZ',
  '信号次数': 42,
  '平均收益': -0.003077153602621785,
  '胜率': 0.2619047619047619},
 {'code': '000068',
  'ts_code': '000068.SZ',
  '信号次数': 45,
  '平均收益': 0.02929995653591127,
  '胜率': 0.3111111111111111},
 {'code': '000069',
  'ts_code': '000069.SZ',
  '信号次数': 55,
  '平均收益': -0.010194895038501831,
  '胜率': 0.2909090909090909},
 {'code': '000070',
  'ts_code': '000070.SZ',
  '信号次数': 41,
  '平均收益': 0.04191053325968353,
  '胜率': 0.2926829268292683},
 {'code': '000078',
  'ts_code': '000078.SZ',
  '信号次数': 46,
  '平均收益': -0.005314585843276695,
  '胜率': 0.2608695652173913},
 {'code': '000088',
  'ts_code': '000088.SZ',
  '信号次数': 55,
  '平均收益': 0.0004945933073443135,
  '胜率': 0.34545454545454546},
 {'code': '000089',
  'ts_code': '000089.SZ',
  '信号次数': 59,
  '平均收益': -0.008327859365467488,
  '胜率': 0.3728813559322034},
 {'code': '000090',
  'ts_code': '000090.SZ',
  '信号次数': 51,
  '平均收益': -0.02141201356244314,
  '胜率': 0.29411764705882354},
 {'code': '000096',
  'ts_code': '000096.SZ',
  '信号次数': 49,
  '平均收益': 0.17218084704745312,
  '胜率': 0.5918367346938775},
 {'code': '000099',
  'ts_code': '000099.SZ',
  '信号次数': 44,
  '平均收益': -0.021299696796268242,
  '胜率': 0.3409090909090909},
 {'code': '000100',
  'ts_code': '000100.SZ',
  '信号次数': 46,
  '平均收益': 0.07279404442614626,
  '胜率': 0.45652173913043476},
 {'code': '000151',
  'ts_code': '000151.SZ',
  '信号次数': 33,
  '平均收益': 0.00013128517177482708,
  '胜率': 0.30303030303030304},
 {'code': '000153',
  'ts_code': '000153.SZ',
  '信号次数': 52,
  '平均收益': -0.004346477670150778,
  '胜率': 0.28846153846153844},
 {'code': '000155',
  'ts_code': '000155.SZ',
  '信号次数': 31,
  '平均收益': 0.07980083489093508,
  '胜率': 0.3870967741935484},
 {'code': '000156',
  'ts_code': '000156.SZ',
  '信号次数': 23,
  '平均收益': -0.006582800309424047,
  '胜率': 0.34782608695652173},
 {'code': '000157',
  'ts_code': '000157.SZ',
  '信号次数': 87,
  '平均收益': -0.02505730346102516,
  '胜率': 0.27586206896551724},
 {'code': '000158',
  'ts_code': '000158.SZ',
  '信号次数': 35,
  '平均收益': 0.029278340322708825,
  '胜率': 0.4857142857142857},
 {'code': '000159',
  'ts_code': '000159.SZ',
  '信号次数': 43,
  '平均收益': -0.0190345436829352,
  '胜率': 0.20930232558139536},
 {'code': '000166',
  'ts_code': '000166.SZ',
  '信号次数': 9,
  '平均收益': -0.014028730918471448,
  '胜率': 0.2222222222222222},
 {'code': '000301',
  'ts_code': '000301.SZ',
  '信号次数': 45,
  '平均收益': 0.035747130395467126,
  '胜率': 0.3111111111111111},
 {'code': '000333',
  'ts_code': '000333.SZ',
  '信号次数': 44,
  '平均收益': 0.025581900149189638,
  '胜率': 0.5},
 {'code': '000338',
  'ts_code': '000338.SZ',
  '信号次数': 46,
  '平均收益': -0.01850364657234842,
  '胜率': 0.17391304347826086},
 {'code': '000400',
  'ts_code': '000400.SZ',
  '信号次数': 67,
  '平均收益': -0.02459183164931536,
  '胜率': 0.2835820895522388},
 {'code': '000401',
  'ts_code': '000401.SZ',
  '信号次数': 51,
  '平均收益': -0.0028723554702427346,
  '胜率': 0.35294117647058826},
 {'code': '000402',
  'ts_code': '000402.SZ',
  '信号次数': 53,
  '平均收益': -0.007026466042042116,
  '胜率': 0.37735849056603776},
 {'code': '000403',
  'ts_code': '000403.SZ',
  '信号次数': 56,
  '平均收益': 0.34116332944568367,
  '胜率': 0.48214285714285715},
 {'code': '000404',
  'ts_code': '000404.SZ',
  '信号次数': 65,
  '平均收益': 0.01346367472732946,
  '胜率': 0.26153846153846155},
 {'code': '000407',
  'ts_code': '000407.SZ',
  '信号次数': 46,
  '平均收益': -0.02786517099141482,
  '胜率': 0.2608695652173913},
 {'code': '000408',
  'ts_code': '000408.SZ',
  '信号次数': 75,
  '平均收益': 0.08631186622860922,
  '胜率': 0.37333333333333335},
 {'code': '000409',
  'ts_code': '000409.SZ',
  '信号次数': 66,
  '平均收益': 0.012324386622393381,
  '胜率': 0.4393939393939394},
 {'code': '000410',
  'ts_code': '000410.SZ',
  '信号次数': 48,
  '平均收益': -0.04088058569638626,
  '胜率': 0.20833333333333334},
 {'code': '000411',
  'ts_code': '000411.SZ',
  '信号次数': 55,
  '平均收益': 0.010830143411727958,
  '胜率': 0.2909090909090909},
 {'code': '000415',
  'ts_code': '000415.SZ',
  '信号次数': 57,
  '平均收益': 0.01101578955822105,
  '胜率': 0.3157894736842105},
 {'code': '000417',
  'ts_code': '000417.SZ',
  '信号次数': 64,
  '平均收益': -0.00456644303456223,
  '胜率': 0.28125},
 {'code': '000419',
  'ts_code': '000419.SZ',
  '信号次数': 43,
  '平均收益': -0.010524840002576129,
  '胜率': 0.32558139534883723},
 {'code': '000420',
  'ts_code': '000420.SZ',
  '信号次数': 50,
  '平均收益': 0.07527631445162071,
  '胜率': 0.36},
 {'code': '000421',
  'ts_code': '000421.SZ',
  '信号次数': 42,
  '平均收益': 0.01262291134672096,
  '胜率': 0.30952380952380953},
 {'code': '000422',
  'ts_code': '000422.SZ',
  '信号次数': 56,
  '平均收益': -0.02603608049884993,
  '胜率': 0.30357142857142855},
 {'code': '000423',
  'ts_code': '000423.SZ',
  '信号次数': 71,
  '平均收益': 0.007573347061570287,
  '胜率': 0.2535211267605634},
 {'code': '000425',
  'ts_code': '000425.SZ',
  '信号次数': 61,
  '平均收益': -0.03127457729236501,
  '胜率': 0.19672131147540983},
 {'code': '000426',
  'ts_code': '000426.SZ',
  '信号次数': 59,
  '平均收益': 0.035001220203914704,
  '胜率': 0.3389830508474576},
 {'code': '000428',
  'ts_code': '000428.SZ',
  '信号次数': 55,
  '平均收益': 0.0003754100112619825,
  '胜率': 0.3090909090909091},
 {'code': '000429',
  'ts_code': '000429.SZ',
  '信号次数': 40,
  '平均收益': -0.01069445692132676,
  '胜率': 0.2},
 {'code': '000498',
  'ts_code': '000498.SZ',
  '信号次数': 53,
  '平均收益': 0.016893517466714924,
  '胜率': 0.4528301886792453},
 {'code': '000501',
  'ts_code': '000501.SZ',
  '信号次数': 60,
  '平均收益': -0.007388841793913992,
  '胜率': 0.35},
 {'code': '000503',
  'ts_code': '000503.SZ',
  '信号次数': 89,
  '平均收益': 0.0727620762163187,
  '胜率': 0.42696629213483145},
 {'code': '000505',
  'ts_code': '000505.SZ',
  '信号次数': 52,
  '平均收益': 0.10528758253530435,
  '胜率': 0.25},
 {'code': '000506',
  'ts_code': '000506.SZ',
  '信号次数': 66,
  '平均收益': 0.08986557818151854,
  '胜率': 0.4696969696969697},
 {'code': '000507',
  'ts_code': '000507.SZ',
  '信号次数': 53,
  '平均收益': -0.027816878596430096,
  '胜率': 0.20754716981132076},
 {'code': '000509',
  'ts_code': '000509.SZ',
  '信号次数': 68,
  '平均收益': 0.02026135688195365,
  '胜率': 0.38235294117647056},
 {'code': '000510',
  'ts_code': '000510.SZ',
  '信号次数': 63,
  '平均收益': 0.08536916470558586,
  '胜率': 0.49206349206349204},
 {'code': '000513',
  'ts_code': '000513.SZ',
  '信号次数': 78,
  '平均收益': -0.006889476138383901,
  '胜率': 0.2692307692307692},
 {'code': '000514',
  'ts_code': '000514.SZ',
  '信号次数': 54,
  '平均收益': -0.013485471127345341,
  '胜率': 0.24074074074074073},
 {'code': '000516',
  'ts_code': '000516.SZ',
  '信号次数': 73,
  '平均收益': -0.009324754835806127,
  '胜率': 0.2602739726027397},
 {'code': '000517',
  'ts_code': '000517.SZ',
  '信号次数': 46,
  '平均收益': 0.004121191129437244,
  '胜率': 0.21739130434782608},
 {'code': '000519',
  'ts_code': '000519.SZ',
  '信号次数': 57,
  '平均收益': -0.026154769121984077,
  '胜率': 0.22807017543859648},
 {'code': '000520',
  'ts_code': '000520.SZ',
  '信号次数': 34,
  '平均收益': 0.01236027648599029,
  '胜率': 0.29411764705882354},
 {'code': '000521',
  'ts_code': '000521.SZ',
  '信号次数': 58,
  '平均收益': 0.05181863346073861,
  '胜率': 0.3620689655172414},
 {'code': '000523',
  'ts_code': '000523.SZ',
  '信号次数': 68,
  '平均收益': 0.014517600490831544,
  '胜率': 0.3235294117647059},
 {'code': '000524',
  'ts_code': '000524.SZ',
  '信号次数': 62,
  '平均收益': -0.00026747722129807244,
  '胜率': 0.25806451612903225},
 {'code': '000525',
  'ts_code': '000525.SZ',
  '信号次数': 58,
  '平均收益': -0.01283746609551845,
  '胜率': 0.29310344827586204},
 {'code': '000526',
  'ts_code': '000526.SZ',
  '信号次数': 70,
  '平均收益': 0.03043072234441656,
  '胜率': 0.44285714285714284},
 {'code': '000528',
  'ts_code': '000528.SZ',
  '信号次数': 76,
  '平均收益': -0.0015537008679318582,
  '胜率': 0.25},
 {'code': '000529',
  'ts_code': '000529.SZ',
  '信号次数': 41,
  '平均收益': -0.00317627343142963,
  '胜率': 0.2926829268292683},
 {'code': '000530',
  'ts_code': '000530.SZ',
  '信号次数': 53,
  '平均收益': 0.030208183085414925,
  '胜率': 0.3584905660377358},
 {'code': '000531',
  'ts_code': '000531.SZ',
  '信号次数': 63,
  '平均收益': 0.018692994089809456,
  '胜率': 0.3492063492063492},
 {'code': '000532',
  'ts_code': '000532.SZ',
  '信号次数': 53,
  '平均收益': 0.017076503741067468,
  '胜率': 0.4339622641509434},
 {'code': '000533',
  'ts_code': '000533.SZ',
  '信号次数': 54,
  '平均收益': 0.007418877085975034,
  '胜率': 0.24074074074074073},
 {'code': '000534',
  'ts_code': '000534.SZ',
  '信号次数': 60,
  '平均收益': -0.016609268678201835,
  '胜率': 0.23333333333333334},
 {'code': '000536',
  'ts_code': '000536.SZ',
  '信号次数': 43,
  '平均收益': 0.014651183922812923,
  '胜率': 0.3953488372093023},
 {'code': '000537',
  'ts_code': '000537.SZ',
  '信号次数': 61,
  '平均收益': -0.010135821191102637,
  '胜率': 0.32786885245901637},
 {'code': '000538',
  'ts_code': '000538.SZ',
  '信号次数': 75,
  '平均收益': 0.0007870824194185957,
  '胜率': 0.18666666666666668},
 {'code': '000539',
  'ts_code': '000539.SZ',
  '信号次数': 58,
  '平均收益': 0.030706616084598216,
  '胜率': 0.25862068965517243},
 {'code': '000541',
  'ts_code': '000541.SZ',
  '信号次数': 55,
  '平均收益': 0.010142406705837957,
  '胜率': 0.38181818181818183},
 {'code': '000543',
  'ts_code': '000543.SZ',
  '信号次数': 49,
  '平均收益': 0.030415878746187182,
  '胜率': 0.2653061224489796},
 {'code': '000544',
  'ts_code': '000544.SZ',
  '信号次数': 66,
  '平均收益': -0.03194862815272753,
  '胜率': 0.25757575757575757},
 {'code': '000545',
  'ts_code': '000545.SZ',
  '信号次数': 63,
  '平均收益': 0.05052393935507027,
  '胜率': 0.36507936507936506},
 {'code': '000546',
  'ts_code': '000546.SZ',
  '信号次数': 48,
  '平均收益': 0.09057857592545081,
  '胜率': 0.4375},
 {'code': '000547',
  'ts_code': '000547.SZ',
  '信号次数': 62,
  '平均收益': 0.11290287292790524,
  '胜率': 0.3548387096774194},
 {'code': '000548',
  'ts_code': '000548.SZ',
  '信号次数': 50,
  '平均收益': 0.021134997454304454,
  '胜率': 0.3},
 {'code': '000550',
  'ts_code': '000550.SZ',
  '信号次数': 63,
  '平均收益': 0.019843165275228353,
  '胜率': 0.36507936507936506},
 {'code': '000551',
  'ts_code': '000551.SZ',
  '信号次数': 70,
  '平均收益': -0.042829567839304576,
  '胜率': 0.2714285714285714},
 {'code': '000552',
  'ts_code': '000552.SZ',
  '信号次数': 50,
  '平均收益': -0.042484762927029074,
  '胜率': 0.12},
 {'code': '000553',
  'ts_code': '000553.SZ',
  '信号次数': 50,
  '平均收益': 0.07865382041176872,
  '胜率': 0.42},
 {'code': '000554',
  'ts_code': '000554.SZ',
  '信号次数': 67,
  '平均收益': -0.020510803298915282,
  '胜率': 0.23880597014925373},
 {'code': '000555',
  'ts_code': '000555.SZ',
  '信号次数': 66,
  '平均收益': 0.022684129494156317,
  '胜率': 0.2727272727272727},
 {'code': '000557',
  'ts_code': '000557.SZ',
  '信号次数': 72,
  '平均收益': 0.055625324799587456,
  '胜率': 0.4027777777777778},
 {'code': '000558',
  'ts_code': '000558.SZ',
  '信号次数': 49,
  '平均收益': 0.10156884913143677,
  '胜率': 0.32653061224489793},
 {'code': '000559',
  'ts_code': '000559.SZ',
  '信号次数': 63,
  '平均收益': 0.014749004041029651,
  '胜率': 0.23809523809523808},
 {'code': '000560',
  'ts_code': '000560.SZ',
  '信号次数': 53,
  '平均收益': 0.04338097324549656,
  '胜率': 0.4339622641509434},
 {'code': '000561',
  'ts_code': '000561.SZ',
  '信号次数': 55,
  '平均收益': 0.1186478912920079,
  '胜率': 0.34545454545454546},
 {'code': '000563',
  'ts_code': '000563.SZ',
  '信号次数': 57,
  '平均收益': -0.02431494395315315,
  '胜率': 0.17543859649122806},
 {'code': '000564',
  'ts_code': '000564.SZ',
  '信号次数': 49,
  '平均收益': -0.00128723522917053,
  '胜率': 0.3877551020408163},
 {'code': '000565',
  'ts_code': '000565.SZ',
  '信号次数': 82,
  '平均收益': -0.01897827092465624,
  '胜率': 0.1951219512195122},
 {'code': '000566',
  'ts_code': '000566.SZ',
  '信号次数': 70,
  '平均收益': 0.10525404998229496,
  '胜率': 0.35714285714285715},
 {'code': '000567',
  'ts_code': '000567.SZ',
  '信号次数': 89,
  '平均收益': -0.001180131281087691,
  '胜率': 0.3258426966292135},
 {'code': '000568',
  'ts_code': '000568.SZ',
  '信号次数': 110,
  '平均收益': -0.0013673205971087364,
  '胜率': 0.3181818181818182},
 {'code': '000570',
  'ts_code': '000570.SZ',
  '信号次数': 55,
  '平均收益': 0.02747724158222528,
  '胜率': 0.4},
 {'code': '000571',
  'ts_code': '000571.SZ',
  '信号次数': 76,
  '平均收益': 0.018399829864822737,
  '胜率': 0.34210526315789475},
 {'code': '000572',
  'ts_code': '000572.SZ',
  '信号次数': 57,
  '平均收益': 0.03165232384324626,
  '胜率': 0.38596491228070173},
 {'code': '000573',
  'ts_code': '000573.SZ',
  '信号次数': 52,
  '平均收益': 0.012431356815901297,
  '胜率': 0.2692307692307692},
 {'code': '000576',
  'ts_code': '000576.SZ',
  '信号次数': 66,
  '平均收益': -0.02016746946984563,
  '胜率': 0.2878787878787879},
 {'code': '000581',
  'ts_code': '000581.SZ',
  '信号次数': 63,
  '平均收益': 0.013799343226022115,
  '胜率': 0.42857142857142855},
 {'code': '000582',
  'ts_code': '000582.SZ',
  '信号次数': 59,
  '平均收益': -0.010988125604659513,
  '胜率': 0.4745762711864407},
 {'code': '000586',
  'ts_code': '000586.SZ',
  '信号次数': 50,
  '平均收益': 0.0420193514516691,
  '胜率': 0.32},
 {'code': '000589',
  'ts_code': '000589.SZ',
  '信号次数': 70,
  '平均收益': 0.007021606412873999,
  '胜率': 0.2714285714285714},
 {'code': '000590',
  'ts_code': '000590.SZ',
  '信号次数': 46,
  '平均收益': 0.06786587505056997,
  '胜率': 0.2608695652173913},
 {'code': '000591',
  'ts_code': '000591.SZ',
  '信号次数': 45,
  '平均收益': -0.0069903523063836945,
  '胜率': 0.26666666666666666},
 {'code': '000592',
  'ts_code': '000592.SZ',
  '信号次数': 34,
  '平均收益': -0.04782461471707472,
  '胜率': 0.14705882352941177},
 {'code': '000593',
  'ts_code': '000593.SZ',
  '信号次数': 47,
  '平均收益': -0.03326401105719892,
  '胜率': 0.2127659574468085},
 {'code': '000596',
  'ts_code': '000596.SZ',
  '信号次数': 62,
  '平均收益': -0.016538712336852446,
  '胜率': 0.22580645161290322},
 {'code': '000597',
  'ts_code': '000597.SZ',
  '信号次数': 65,
  '平均收益': 0.022724502472748133,
  '胜率': 0.27692307692307694},
 {'code': '000598',
  'ts_code': '000598.SZ',
  '信号次数': 60,
  '平均收益': 0.0037042038925718572,
  '胜率': 0.36666666666666664},
 {'code': '000599',
  'ts_code': '000599.SZ',
  '信号次数': 46,
  '平均收益': 0.0646426340616934,
  '胜率': 0.41304347826086957},
 {'code': '000600',
  'ts_code': '000600.SZ',
  '信号次数': 60,
  '平均收益': -0.003804519502340611,
  '胜率': 0.2833333333333333},
 {'code': '000601',
  'ts_code': '000601.SZ',
  '信号次数': 37,
  '平均收益': -0.005731023869080751,
  '胜率': 0.35135135135135137},
 {'code': '000603',
  'ts_code': '000603.SZ',
  '信号次数': 71,
  '平均收益': 0.13178371384615545,
  '胜率': 0.4788732394366197},
 {'code': '000605',
  'ts_code': '000605.SZ',
  '信号次数': 54,
  '平均收益': 0.09148686847317145,
  '胜率': 0.3333333333333333},
 {'code': '000607',
  'ts_code': '000607.SZ',
  '信号次数': 44,
  '平均收益': 0.019590830625395392,
  '胜率': 0.45454545454545453},
 {'code': '000610',
  'ts_code': '000610.SZ',
  '信号次数': 44,
  '平均收益': -0.02998018864264991,
  '胜率': 0.25},
 {'code': '000612',
  'ts_code': '000612.SZ',
  '信号次数': 64,
  '平均收益': -0.03177336513482604,
  '胜率': 0.265625},
 {'code': '000617',
  'ts_code': '000617.SZ',
  '信号次数': 48,
  '平均收益': 0.027957010378092607,
  '胜率': 0.2708333333333333},
 {'code': '000619',
  'ts_code': '000619.SZ',
  '信号次数': 55,
  '平均收益': 0.043532322273873804,
  '胜率': 0.3090909090909091},
 {'code': '000620',
  'ts_code': '000620.SZ',
  '信号次数': 37,
  '平均收益': -0.06531143001245891,
  '胜率': 0.13513513513513514},
 {'code': '000623',
  'ts_code': '000623.SZ',
  '信号次数': 69,